#!/usr/bin/env python3
"""Build a self-contained HTML capacity report from the generated artifacts.

Everything (tables + charts) is embedded, so the report opens standalone with no server and
no network. Source numbers are read straight from ``outputs/notebook_02`` so the report cannot
disagree with the artifacts.
"""

from __future__ import annotations

import base64
from pathlib import Path

import pandas as pd


REPO_ROOT = Path(__file__).resolve().parents[1]
OUTPUT_DIR = REPO_ROOT / "outputs" / "notebook_02"
VISUAL_DIR = REPO_ROOT / "visuals"
REPORT_DIR = REPO_ROOT / "outputs" / "report"

CHART_FILES = (
    "precision_recall_comparison.png",
    "leakage_comparison.png",
    "capacity_lift_by_model.png",
    "calibration_curve.png",
    "feature_importance.png",
    "distribution_shift.png",
    "subgroup_errors.png",
    "cumulative_gains.png",
)


def _table(name: str, drop: tuple[str, ...] = ()) -> str:
    frame = pd.read_csv(OUTPUT_DIR / name)
    if drop:
        frame = frame.drop(columns=[column for column in drop if column in frame.columns])
    return frame.to_html(index=False, border=0, float_format=lambda value: f"{value:,.4f}".rstrip("0").rstrip("."))


def _image(path: Path) -> str:
    encoded = base64.b64encode(path.read_bytes()).decode("ascii")
    return f'<img src="data:image/png;base64,{encoded}" alt="{path.stem}"/>'


def main() -> None:
    REPORT_DIR.mkdir(parents=True, exist_ok=True)
    impact = (OUTPUT_DIR / "impact_statement.md").read_text().strip()

    sections = [
        ("Capacity policy (with 95% CIs and p-values)", "capacity_table.csv"),
        ("Model performance", "model_metrics.csv"),
        ("Leakage cost (measured)", "leakage_comparison.csv"),
        ("Calibration under drift", "calibration_metrics.csv"),
        ("Distribution shift (PSI)", "distribution_shift.csv"),
        ("Subgroup error analysis (descriptive)", "subgroup_errors.csv"),
        ("Tuning sensitivity", "tuning_sensitivity.csv"),
        ("Feature importance (predictive)", "feature_importance.csv"),
    ]
    tables = "\n".join(
        f'<section><h2>{title}</h2>{_table(name)}</section>' for title, name in sections
    )
    charts = "\n".join(
        f'<figure>{_image(VISUAL_DIR / name)}<figcaption>{name.replace("_", " ").replace(".png", "")}</figcaption></figure>'
        for name in CHART_FILES
        if (VISUAL_DIR / name).exists()
    )

    html = f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>Campaign Prophet — capacity report</title>
<style>
  body {{ font-family: -apple-system, Segoe UI, Roboto, sans-serif; margin: 2rem auto; max-width: 1100px; color: #1c1c1c; padding: 0 1rem; }}
  h1 {{ margin-bottom: 0.2rem; }}
  h2 {{ margin-top: 2rem; border-bottom: 1px solid #ddd; padding-bottom: 0.3rem; }}
  table {{ border-collapse: collapse; width: 100%; margin: 0.5rem 0; font-size: 0.86rem; }}
  th, td {{ border: 1px solid #e2e2e2; padding: 0.35rem 0.5rem; text-align: right; }}
  th {{ background: #f6f6f6; }}
  td:first-child, th:first-child {{ text-align: left; }}
  .impact {{ background: #eef7f2; border-left: 4px solid #1D9E75; padding: 0.8rem 1rem; }}
  figure {{ margin: 1rem 0; }} img {{ max-width: 100%; border: 1px solid #eee; }}
  figcaption {{ font-size: 0.8rem; color: #666; }}
  .note {{ color: #666; font-size: 0.85rem; }}
</style>
</head>
<body>
<h1>Campaign Prophet — capacity report</h1>
<p class="note">Pre-contact decision support on the UCI Bank Marketing dataset. Generated from the committed artifacts; descriptive only, not causal, not a financial recommendation.</p>
<p class="impact">{impact}</p>
{tables}
<section><h2>Charts</h2>{charts}</section>
<p class="note">Source: outputs/notebook_02 (regenerated by scripts/run_modeling.py).</p>
</body>
</html>
"""
    report_path = REPORT_DIR / "capacity_report.html"
    report_path.write_text(html, encoding="utf-8")
    print(f"Wrote {report_path.relative_to(REPO_ROOT)} ({len(html):,} bytes)")


if __name__ == "__main__":
    main()
